version: '3.8'
services:
  postgres:
    image: postgres:14.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest    
    ports:
      - "5434:5432"
  test-db:
    image: postgres:14.3
    container_name: test-db-1
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest    
    
  